jobs:
  default:
    source:
      pattern: "dist/**" # 匹配 dist 目录下的所有文件
      strip: "dist" # 去掉 dist 前缀
    dist: "$MY_S3_DSN" # 从环境变量中获取目标 DSN
    rules:
      # 给图标和 favicon 设置 300 秒缓存
      - pattern: "{icons/**,favicon.ico}"
        headers:
          "Cache-Control": "public, max-age=300"
      # 给哈希命名的文件设置永久缓存
      - pattern: "assets/**"
        headers:
          "Cache-Control": "public, max-age=31536000, immutable"
      # 给 index.html 设置 3 秒缓存
      # 同时设置 index 为 1，使得 index.html 在所有文件之后再上传
      - pattern: "index.html"
        index: 1
        headers:
          "Cache-Control": "public, max-age=3"

  doc:
    source:
      pattern: ".vitepress/dist/**"
      strip: ".vitepress/dist"
    dist:
      type: "s3" # 使用 s3 上传
      dsn: "s3://path/to/your/bucket/path/" # 目标 DSN
    rules:
      # 给所有文件设置 1 秒缓存，防止缓存穿透
      - pattern: "**/*"
        headers:
          "Cache-Control": "@second"
      # 给哈希命名的文件设置永久缓存
      # 别名 @forever 在 utils/alias.go 中定义，等效于 public, max-age=31536000, immutable
      - pattern: "assets/**"
        headers:
          "Cache-Control": "@forever"
      # 给所有 html 文件设置 index 为 1，使 html 文件在其他文件之后上传
      - pattern: "**/*.html"
        index: 1
      # 最后上传 index.html 和 hashmap.json，并取消缓存
      - pattern: "{index.html,hashmap.json}"
        index: 2
        headers:
          "Cache-Control": "no-cache"
